[project]
name = "nametagfinder"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.10.3",
    "matplotlib-inline==0.1.7",
    "numpy==2.2.6",
    "opencv-python==4.12.0.88",
    "pandas==2.3.1",
    "seaborn==0.13.2",
    "ultralytics==8.3.166",
]
