[project]
name = "strawberrydetection-yolo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.10.3",
    "opencv-python==4.11.0.86",
    "pandas==2.2.3",
    "seaborn==0.13.2",
    "ultralytics==8.3.140",
]
